import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');
const isTablet = width >= 768;

export const homeScreenStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: '#F8F9FA',
  },
  mainContainer: {
    flex: 1,
  },
  container: {
    flex: 1,
    backgroundColor: '#F8F9FA',
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: isTablet ? 30 : 20,
    paddingVertical: isTablet ? 24 : 16,
    backgroundColor: 'white',
  },
  storeInfo: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  logo: {
    width: isTablet ? 56 : 40,
    height: isTablet ? 56 : 40,
    marginRight: isTablet ? 16 : 12,
  },
  storeDetails: {
    flex: 1,
  },
  storeName: {
    fontSize: isTablet ? 24 : 18,
    fontWeight: '700',
    color: '#1A1A1A',
    marginBottom: isTablet ? 4 : 2,
  },
  userName: {
    fontSize: isTablet ? 16 : 13,
    color: '#8E8E93',
    fontWeight: '500',
  },
  logoutButton: {
    width: isTablet ? 48 : 40,
    height: isTablet ? 48 : 40,
    borderRadius: isTablet ? 24 : 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  salesCard: {
    backgroundColor: 'white',
    marginHorizontal: isTablet ? 30 : 20,
    marginTop: isTablet ? 20 : 16,
    paddingTop: isTablet ? 32 : 24,
    paddingBottom: isTablet ? 36 : 28,
    paddingHorizontal: isTablet ? 32 : 20,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: isTablet ? 20 : 12,
    minHeight: isTablet ? 120 : 100,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 6,
    elevation: 4,
  },
  salesLabel: {
    fontSize: isTablet ? 16 : 14,
    color: '#8E8E93',
    fontWeight: '600',
    marginBottom: isTablet ? 12 : 8,
    letterSpacing: 0.5,
  },
  salesValue: {
    fontSize: isTablet ? 38 : 32,
    fontWeight: '800',
    color: '#007AFF',
    textAlign: 'center',
    letterSpacing: -0.5,
    lineHeight: isTablet ? 42 : 36,
  },
  quickMenuCard: {
    backgroundColor: 'white',
    marginHorizontal: isTablet ? 30 : 20,
    marginTop: isTablet ? 20 : 16,
    borderRadius: isTablet ? 16 : 12,
    paddingVertical: isTablet ? 28 : 20,
    paddingHorizontal: isTablet ? 28 : 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  quickMenuTitle: {
    fontSize: isTablet ? 20 : 16,
    fontWeight: '600',
    color: '#1A1A1A',
    marginBottom: isTablet ? 20 : 16,
  },
  quickMenuGrid: {
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  quickMenuItem: {
    alignItems: 'center',
    flex: 1,
  },
  quickMenuIcon: {
    width: isTablet ? 64 : 48,
    height: isTablet ? 64 : 48,
    borderRadius: isTablet ? 32 : 24,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: isTablet ? 12 : 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  quickMenuLabel: {
    fontSize: isTablet ? 16 : 12,
    fontWeight: '500',
    color: '#374151',
    textAlign: 'center',
  },
  calendarCard: {
    backgroundColor: 'white',
    marginHorizontal: isTablet ? 30 : 20,
    marginTop: isTablet ? 20 : 16,
    marginBottom: isTablet ? 30 : 20,
    borderRadius: isTablet ? 16 : 12,
    paddingVertical: isTablet ? 28 : 20,
    paddingHorizontal: isTablet ? 28 : 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
  },
  calendarHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  calendarTitle: {
    fontSize: isTablet ? 20 : 16,
    fontWeight: '600',
    color: '#1A1A1A',
  },
  addScheduleButton: {
    width: isTablet ? 40 : 32,
    height: isTablet ? 40 : 32,
    borderRadius: isTablet ? 20 : 16,
    backgroundColor: '#F0F8FF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  dateNavigation: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 20,
    paddingHorizontal: 12,
  },
  dateNavButton: {
    width: isTablet ? 40 : 32,
    height: isTablet ? 40 : 32,
    borderRadius: isTablet ? 20 : 16,
    backgroundColor: '#F0F8FF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  dateDisplay: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 12,
  },
  dateContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  dateText: {
    fontSize: isTablet ? 20 : 16,
    color: '#1A1A1A',
    fontWeight: '600',
  },
  todayBadge: {
    backgroundColor: '#F0F8FF',
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 2,
    marginLeft: 10,
    borderWidth: 0.5,
    borderColor: '#007AFF',
  },
  todayBadgeText: {
    fontSize: 12,
    color: '#007AFF',
    fontWeight: '500',
  },
  scheduleList: {
    minHeight: 120,
  },
  scheduleItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: isTablet ? 16 : 12,
    borderBottomWidth: 1,
    borderBottomColor: '#F0F0F0',
  },
  scheduleItemCompleted: {
    backgroundColor: '#F8F9FA',
    opacity: 0.7,
  },
  scheduleTime: {
    width: isTablet ? 80 : 60,
    marginRight: isTablet ? 16 : 12,
  },
  timeText: {
    fontSize: isTablet ? 16 : 12,
    color: '#8E8E93',
    fontWeight: '500',
  },
  timeTextCompleted: {
    textDecorationLine: 'line-through',
    color: '#C7C7CC',
  },
  scheduleContent: {
    flex: 1,
  },
  scheduleTitle: {
    fontSize: isTablet ? 18 : 14,
    fontWeight: '500',
    color: '#1A1A1A',
  },
  scheduleTitleCompleted: {
    textDecorationLine: 'line-through',
    color: '#C7C7CC',
  },
  scheduleActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: isTablet ? 12 : 8,
  },
  completeButton: {
    width: isTablet ? 32 : 24,
    height: isTablet ? 32 : 24,
    borderRadius: isTablet ? 16 : 12,
    borderWidth: 1.5,
    borderColor: '#4CAF50',
    backgroundColor: 'transparent',
    justifyContent: 'center',
    alignItems: 'center',
  },
  completeButtonActive: {
    backgroundColor: '#4CAF50',
    borderColor: '#4CAF50',
  },
  deleteButton: {
    width: isTablet ? 32 : 24,
    height: isTablet ? 32 : 24,
    borderRadius: isTablet ? 16 : 12,
    borderWidth: 1.5,
    borderColor: '#FF3B30',
    backgroundColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
  },
  noSchedule: {
    alignItems: 'center',
    paddingVertical: isTablet ? 32 : 24,
  },
  noScheduleText: {
    fontSize: isTablet ? 18 : 14,
    color: '#8E8E93',
    marginTop: isTablet ? 12 : 8,
    marginBottom: isTablet ? 16 : 12,
  },
  addFirstSchedule: {
    paddingHorizontal: isTablet ? 20 : 16,
    paddingVertical: isTablet ? 12 : 8,
    backgroundColor: '#F0F8FF',
    borderRadius: isTablet ? 20 : 16,
  },
  addFirstScheduleText: {
    fontSize: isTablet ? 16 : 12,
    color: '#007AFF',
    fontWeight: '500',
  },
  showMoreButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 8,
    marginTop: 4,
    borderTopWidth: 1,
    borderTopColor: '#F0F0F0',
  },
  showMoreText: {
    fontSize: isTablet ? 16 : 13,
    color: '#007AFF',
    fontWeight: '500',
    marginRight: isTablet ? 6 : 4,
  },
  dockContainer: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: 'row',
    justifyContent: 'space-around',
    backgroundColor: 'white',
    paddingVertical: isTablet ? 20 : 16,
    paddingBottom: isTablet ? 24 : 20,
    borderTopWidth: 1,
    borderTopColor: '#F0F0F0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: -2 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 8,
  },
  dockItem: {
    alignItems: 'center',
    flex: 1,
    paddingVertical: isTablet ? 12 : 10,
  },
  dockLabel: {
    fontSize: isTablet ? 14 : 12,
    fontWeight: '500',
    textAlign: 'center',
    marginTop: isTablet ? 8 : 6,
  },
  calendarModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  calendarModalContent: {
    backgroundColor: 'white',
    borderRadius: 16,
    margin: 20,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 8,
    elevation: 8,
  },
  calendarModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  calendarModalTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#1A1A1A',
  },
  calendarCloseButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#F8F9FA',
    justifyContent: 'center',
    alignItems: 'center',
  },
});