import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#f8f9fa',
    },
    scrollView: {
      flex: 1,
    },
    scrollContent: {
      paddingBottom: 80,
    },
    header: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: 20,
      backgroundColor: '#ffffff',
      borderBottomWidth: 1,
      borderBottomColor: '#e9ecef',
    },
    title: {
      fontSize: 24,
      fontWeight: 'bold',
      color: '#212529',
    },
    addButton: {
      backgroundColor: '#4A90E2',
      paddingHorizontal: 16,
      paddingVertical: 8,
      borderRadius: 8,
    },
    addButtonText: {
      color: '#ffffff',
      fontWeight: '600',
      fontSize: 14,
    },
    summaryContainer: {
      flexDirection: 'row',
      padding: 20,
      gap: 12,
    },
    summaryCard: {
      flex: 1,
      backgroundColor: '#ffffff',
      padding: 20,
      borderRadius: 12,
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    summaryLabel: {
      fontSize: 14,
      color: '#6c757d',
      marginBottom: 8,
    },
    summaryAmount: {
      fontSize: 20,
      fontWeight: 'bold',
      color: '#212529',
      marginBottom: 4,
    },
    summaryCount: {
      fontSize: 12,
      color: '#6c757d',
    },
    chartContainer: {
      backgroundColor: '#ffffff',
      margin: 20,
      borderRadius: 12,
      padding: 20,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    chartHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 20,
    },
    chartTitle: {
      fontSize: 18,
      fontWeight: 'bold',
      color: '#212529',
    },
    chartToggle: {
      flexDirection: 'row',
      backgroundColor: '#f8f9fa',
      borderRadius: 8,
      padding: 2,
    },
    toggleButton: {
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 6,
    },
    activeToggle: {
      backgroundColor: '#4A90E2',
    },
    toggleText: {
      fontSize: 14,
      color: '#6c757d',
    },
    activeToggleText: {
      color: '#ffffff',
      fontWeight: '600',
    },
    chart: {
      marginVertical: 8,
      borderRadius: 16,
    },
    listContainer: {
      backgroundColor: '#ffffff',
      margin: 20,
      marginTop: 0,
      borderRadius: 12,
      padding: 20,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 3,
    },
    listTitle: {
      fontSize: 18,
      fontWeight: 'bold',
      color: '#212529',
      marginBottom: 16,
    },
    emptyState: {
      alignItems: 'center',
      paddingVertical: 40,
    },
    emptyText: {
      fontSize: 16,
      color: '#6c757d',
    },
    salesItem: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: 16,
      borderBottomWidth: 1,
      borderBottomColor: '#e9ecef',
    },
    salesInfo: {
      flex: 1,
    },
    salesAmount: {
      fontSize: 18,
      fontWeight: 'bold',
      color: '#212529',
      marginBottom: 4,
    },
    salesDescription: {
      fontSize: 14,
      color: '#495057',
      marginBottom: 4,
    },
    salesDate: {
      fontSize: 12,
      color: '#6c757d',
    },
    salesActions: {
      flexDirection: 'row',
      gap: 8,
    },
    editButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: '#F0F8FF',
      justifyContent: 'center',
      alignItems: 'center',
    },
    deleteButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: '#FFF0F0',
      justifyContent: 'center',
      alignItems: 'center',
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0, 0, 0, 0.5)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    modalContent: {
      padding: 24,
    },
    modalTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      color: '#212529',
      marginBottom: 24,
      textAlign: 'center',
    },
    inputContainer: {
      marginBottom: 20,
    },
    inputLabel: {
      fontSize: 14,
      fontWeight: '600',
      color: '#495057',
      marginBottom: 8,
    },
    input: {
      borderWidth: 1,
      borderColor: '#ced4da',
      borderRadius: 8,
      padding: 12,
      fontSize: 16,
      backgroundColor: '#ffffff',
    },
    modalButtons: {
      flexDirection: 'row',
      gap: 12,
      marginTop: 8,
    },
    cancelButton: {
      flex: 1,
      backgroundColor: '#6c757d',
      paddingVertical: 12,
      borderRadius: 8,
      alignItems: 'center',
    },
    cancelButtonText: {
      color: '#ffffff',
      fontSize: 16,
      fontWeight: '600',
    },
    confirmButton: {
      flex: 1,
      backgroundColor: '#4A90E2',
      paddingVertical: 12,
      borderRadius: 8,
      alignItems: 'center',
    },
    confirmButtonText: {
      color: '#ffffff',
      fontSize: 16,
      fontWeight: '600',
    },
    paymentToggle: {
      flexDirection: 'row',
      backgroundColor: '#f8f9fa',
      borderRadius: 8,
      padding: 2,
    },
    paymentButton: {
      flex: 1,
      paddingVertical: 10,
      alignItems: 'center',
      borderRadius: 6,
    },
    activePayment: {
      backgroundColor: '#4A90E2',
    },
    paymentText: {
      fontSize: 14,
      color: '#6c757d',
      fontWeight: '600',
    },
    activePaymentText: {
      color: '#ffffff',
    },
    detailModalContent: {
      backgroundColor: '#ffffff',
      borderRadius: 12,
      padding: 0,
      width: '90%',
      maxWidth: 400,
      maxHeight: '80%',
    },
    detailHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: 20,
      borderBottomWidth: 1,
      borderBottomColor: '#e9ecef',
    },
    detailTitle: {
      fontSize: 20,
      fontWeight: 'bold',
      color: '#212529',
    },
    closeButton: {
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: '#f8f9fa',
      justifyContent: 'center',
      alignItems: 'center',
    },
    detailContent: {
      padding: 20,
    },
    detailRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingVertical: 12,
      borderBottomWidth: 1,
      borderBottomColor: '#f1f3f4',
    },
    detailLabel: {
      fontSize: 16,
      color: '#6c757d',
      fontWeight: '500',
    },
    detailValue: {
      fontSize: 16,
      color: '#212529',
      fontWeight: '600',
    },
    detailAmount: {
      fontSize: 18,
      color: '#4A90E2',
      fontWeight: 'bold',
    },
    paymentBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: '#f8f9fa',
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 12,
      gap: 4,
    },
    paymentBadgeText: {
      fontSize: 14,
      fontWeight: '600',
    },
    detailActions: {
      flexDirection: 'row',
      gap: 12,
      marginTop: 20,
      paddingTop: 20,
      borderTopWidth: 1,
      borderTopColor: '#e9ecef',
    },
    detailEditButton: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#F0F8FF',
      paddingVertical: 12,
      borderRadius: 8,
      gap: 6,
    },
    detailEditText: {
      color: '#007AFF',
      fontSize: 16,
      fontWeight: '600',
    },
    detailDeleteButton: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#FFF0F0',
      paddingVertical: 12,
      borderRadius: 8,
      gap: 6,
    },
    detailDeleteText: {
      color: '#FF3B30',
      fontSize: 16,
      fontWeight: '600',
    },
    originalAmount: {
      fontSize: 14,
      color: '#8E8E93',
      textDecorationLine: 'line-through',
      marginTop: 2,
    },
    discountAmount: {
      fontSize: 16,
      color: '#FF3B30',
      fontWeight: '600',
    },
    couponInfo: {
      alignItems: 'flex-end',
    },
    couponName: {
      fontSize: 14,
      color: '#007AFF',
      fontWeight: '500',
    },
    couponDiscount: {
      fontSize: 14,
      color: '#FF3B30',
      fontWeight: '600',
      marginTop: 2,
    },
    pointsUsed: {
      fontSize: 16,
      color: '#FFD700',
      fontWeight: '600',
    },
    dateSelector: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 16,
      paddingHorizontal: 8,
    },
    dateNavButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: '#F0F8FF',
      justifyContent: 'center',
      alignItems: 'center',
    },
    dateDisplay: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 12,
      paddingVertical: 8,
      minWidth: 180,
      justifyContent: 'center',
    },
    dateInfo: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    selectedDateMain: {
      fontSize: 17,
      fontWeight: '600',
      color: '#212529',
      letterSpacing: 0.3,
    },
    todayBadge: {
      backgroundColor: '#F0F8FF',
      borderRadius: 10,
      paddingHorizontal: 8,
      paddingVertical: 2,
      borderWidth: 0.5,
      borderColor: '#007AFF',
    },
    todayText: {
      fontSize: 12,
      color: '#007AFF',
      fontWeight: '500',
    },
    calendarModal: {
      backgroundColor: '#ffffff',
      borderRadius: 12,
      padding: 0,
      width: '90%',
      maxWidth: 400,
    },
    calendarHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: 20,
      borderBottomWidth: 1,
      borderBottomColor: '#e9ecef',
    },
    calendarTitle: {
      fontSize: 18,
      fontWeight: 'bold',
      color: '#212529',
    },
    calendarContent: {
      padding: 20,
    },
    monthYear: {
      fontSize: 16,
      fontWeight: '600',
      color: '#212529',
      textAlign: 'center',
      marginBottom: 20,
    },
    weekDays: {
      flexDirection: 'row',
      marginBottom: 10,
    },
    weekDay: {
      flex: 1,
      alignItems: 'center',
      paddingVertical: 8,
    },
    weekDayText: {
      fontSize: 14,
      color: '#6c757d',
      fontWeight: '500',
    },
    calendarGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
    },
    calendarDay: {
      width: '14.28%',
      aspectRatio: 1,
      alignItems: 'center',
      justifyContent: 'center',
      position: 'relative',
    },
    selectedDay: {
      backgroundColor: '#007AFF',
      borderRadius: 20,
    },
    todayDay: {
      backgroundColor: '#f0f8ff',
      borderRadius: 20,
    },
    calendarDayText: {
      fontSize: 16,
      color: '#212529',
    },
    selectedDayText: {
      color: '#ffffff',
      fontWeight: '600',
    },
    todayDayText: {
      color: '#007AFF',
      fontWeight: '600',
    },
    otherMonthText: {
      color: '#c6c6c6',
    },
    salesDot: {
      position: 'absolute',
      bottom: 4,
      width: 4,
      height: 4,
      borderRadius: 2,
      backgroundColor: '#34C759',
    },
    dayStats: {
      backgroundColor: '#f8f9fa',
      paddingVertical: 8,
      paddingHorizontal: 16,
      borderRadius: 8,
      marginBottom: 16,
      alignItems: 'center',
    },
    dayStatsText: {
      fontSize: 14,
      color: '#495057',
      fontWeight: '500',
    },
    salesMeta: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: 4,
    },
    salesTime: {
      fontSize: 14,
      color: '#6c757d',
      fontWeight: '500',
    },
    customerName: {
      fontSize: 14,
      color: '#6c757d',
    },
    paymentBadgeSmall: {
      marginLeft: 8,
      padding: 2,
    },
    priceRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginBottom: 4,
    },
    showMoreButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 12,
      marginTop: 8,
      borderTopWidth: 1,
      borderTopColor: '#f1f3f4',
    },
    showMoreText: {
      fontSize: 14,
      color: '#007AFF',
      fontWeight: '500',
      marginRight: 6,
    },
    chartTitleContainer: {
      alignItems: 'flex-start',
    },
    chartDateRange: {
      fontSize: 12,
      color: '#8E8E93',
      marginTop: 2,
    },
    chartHint: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      marginTop: 12,
      gap: 4,
    },
    chartHintText: {
      fontSize: 12,
      color: '#8E8E93',
    },
    tooltip: {
      backgroundColor: 'rgba(0, 0, 0, 0.8)',
      borderRadius: 8,
      paddingHorizontal: 12,
      paddingVertical: 8,
      marginTop: 8,
      alignSelf: 'center',
    },
    tooltipContent: {
      alignItems: 'center',
    },
    tooltipTitle: {
      fontSize: 12,
      color: '#ffffff',
      fontWeight: '600',
      marginBottom: 2,
    },
    tooltipAmount: {
      fontSize: 14,
      color: '#ffffff',
      fontWeight: 'bold',
      marginBottom: 1,
    },
    tooltipCount: {
      fontSize: 11,
      color: '#cccccc',
    },
    dateRangeRow: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: 2,
    },
    rangeInstruction: {
      fontSize: 14,
      color: '#6c757d',
      textAlign: 'center',
      marginBottom: 16,
    },
    selectedRangeInfo: {
      backgroundColor: '#f0f8ff',
      padding: 12,
      borderRadius: 8,
      marginBottom: 16,
    },
    selectedRangeText: {
      fontSize: 14,
      color: '#007AFF',
      textAlign: 'center',
      fontWeight: '500',
    },
    rangeDay: {
      backgroundColor: '#e3f2fd',
    },
    rangeStartDay: {
      backgroundColor: '#007AFF',
      borderTopLeftRadius: 20,
      borderBottomLeftRadius: 20,
    },
    rangeEndDay: {
      backgroundColor: '#007AFF',
      borderTopRightRadius: 20,
      borderBottomRightRadius: 20,
    },
    rangeDayText: {
      color: '#ffffff',
      fontWeight: '600',
    },
    disabledButton: {
      opacity: 0.5,
    },
    modalScrollView: {
      maxHeight: '80%',
      width: '90%',
      maxWidth: 400,
      backgroundColor: '#ffffff',
      borderRadius: 12,
    },
    customerSelectButton: {
      borderWidth: 1,
      borderColor: '#ced4da',
      borderRadius: 8,
      padding: 12,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: '#ffffff',
    },
    customerSelectContent: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
    },
    customerInfo: {
      flex: 1,
    },
    customerPoints: {
      alignItems: 'flex-end',
    },
    pointsText: {
      fontSize: 14,
      color: '#FFD700',
      fontWeight: '600',
    },
    couponsText: {
      fontSize: 12,
      color: '#007AFF',
      marginTop: 2,
    },
    customerPhone: {
      fontSize: 12,
      color: '#8E8E93',
      marginTop: 2,
    },
    placeholderText: {
      fontSize: 16,
      color: '#8E8E93',
    },
    serviceSelectButton: {
      borderWidth: 1,
      borderColor: '#ced4da',
      borderRadius: 8,
      padding: 12,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: '#ffffff',
    },
    selectedServiceContent: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
    },
    serviceIcon: {
      width: 40,
      height: 40,
      borderRadius: 20,
      backgroundColor: '#F0F8FF',
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 12,
    },
    serviceInfo: {
      flex: 1,
    },
    serviceName: {
      fontSize: 16,
      fontWeight: '600',
      color: '#212529',
    },
    servicePrice: {
      fontSize: 14,
      color: '#8E8E93',
      marginTop: 2,
    },
    amountAdjustContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 12,
    },
    adjustButton: {
      backgroundColor: '#F0F8FF',
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 6,
      minWidth: 60,
      alignItems: 'center',
    },
    adjustButtonText: {
      fontSize: 12,
      color: '#007AFF',
      fontWeight: '600',
    },
    amountDisplay: {
      flex: 1,
      alignItems: 'center',
      marginHorizontal: 8,
    },
    currentAmount: {
      fontSize: 18,
      fontWeight: 'bold',
      color: '#212529',
    },
    amountInput: {
      borderWidth: 1,
      borderColor: '#ced4da',
      borderRadius: 8,
      padding: 12,
      fontSize: 16,
      backgroundColor: '#ffffff',
      textAlign: 'center',
    },
    couponSection: {
      marginBottom: 16,
    },
    sectionSubtitle: {
      fontSize: 14,
      fontWeight: '600',
      color: '#495057',
      marginBottom: 8,
    },
    couponItem: {
      borderWidth: 1,
      borderColor: '#e9ecef',
      borderRadius: 8,
      padding: 12,
      marginBottom: 8,
      backgroundColor: '#ffffff',
    },
    selectedCouponItem: {
      borderColor: '#007AFF',
      backgroundColor: '#F0F8FF',
    },
    couponValue: {
      fontSize: 12,
      color: '#FF3B30',
      fontWeight: '600',
      marginTop: 4,
    },
    pointsSection: {
      marginTop: 8,
    },
    pointsInputContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    pointsInput: {
      flex: 1,
      borderWidth: 1,
      borderColor: '#ced4da',
      borderRadius: 8,
      padding: 12,
      fontSize: 16,
      backgroundColor: '#ffffff',
    },
    maxPointsButton: {
      backgroundColor: '#FFD700',
      paddingHorizontal: 12,
      paddingVertical: 12,
      borderRadius: 8,
    },
    maxPointsText: {
      fontSize: 14,
      color: '#ffffff',
      fontWeight: '600',
    },
    paymentSummary: {
      backgroundColor: '#f8f9fa',
      borderRadius: 8,
      padding: 16,
      marginBottom: 20,
    },
    summaryRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 8,
    },
    summaryValueLabel: {
      fontSize: 14,
      color: '#6c757d',
    },
    summaryValue: {
      fontSize: 14,
      color: '#212529',
      fontWeight: '600',
    },
    discountValue: {
      fontSize: 14,
      color: '#FF3B30',
      fontWeight: '600',
    },
    totalRow: {
      borderTopWidth: 1,
      borderTopColor: '#e9ecef',
      paddingTop: 8,
      marginTop: 8,
      marginBottom: 0,
    },
    totalLabel: {
      fontSize: 16,
      color: '#212529',
      fontWeight: 'bold',
    },
    totalValue: {
      fontSize: 18,
      color: '#4A90E2',
      fontWeight: 'bold',
    },
    searchModal: {
      backgroundColor: '#ffffff',
      borderRadius: 12,
      padding: 0,
      width: '90%',
      maxWidth: 400,
      maxHeight: '80%',
    },
    guestCustomerSection: {
      borderTopWidth: 1,
      borderTopColor: '#e9ecef',
      paddingTop: 16,
      marginTop: 16,
    },
    guestCustomerButton: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: '#f8f9fa',
      borderWidth: 1,
      borderColor: '#e9ecef',
      borderRadius: 8,
      padding: 16,
      gap: 8,
    },
    guestCustomerText: {
      fontSize: 16,
      color: '#6c757d',
      fontWeight: '500',
    },
    guestCustomerDisplay: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    customerClearButton: {
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 6,
      backgroundColor: '#f8f9fa',
      borderWidth: 1,
      borderColor: '#e9ecef',
      justifyContent: 'center',
      alignItems: 'center',
      marginLeft: 8,
    },
    customerClearText: {
      fontSize: 12,
      color: '#6c757d',
      fontWeight: '500',
    },
    searchHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: 20,
      borderBottomWidth: 1,
      borderBottomColor: '#e9ecef',
    },
    searchTitle: {
      fontSize: 18,
      fontWeight: 'bold',
      color: '#212529',
    },
    searchContent: {
      padding: 20,
    },
    searchInput: {
      borderWidth: 1,
      borderColor: '#ced4da',
      borderRadius: 8,
      padding: 12,
      fontSize: 16,
      backgroundColor: '#ffffff',
      marginBottom: 16,
    },
    customerList: {
      maxHeight: 300,
    },
    customerItem: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      padding: 12,
      borderBottomWidth: 1,
      borderBottomColor: '#f1f3f4',
    },
    customerItemInfo: {
      flex: 1,
    },
    customerItemName: {
      fontSize: 16,
      fontWeight: '600',
      color: '#212529',
    },
    customerItemPhone: {
      fontSize: 14,
      color: '#8E8E93',
      marginTop: 2,
    },
    customerItemMeta: {
      alignItems: 'flex-end',
    },
    customerItemPoints: {
      fontSize: 14,
      color: '#FFD700',
      fontWeight: '600',
    },
    customerItemCoupons: {
      fontSize: 12,
      color: '#007AFF',
      marginTop: 2,
    },
    serviceCard: {
      width: '30%',
      backgroundColor: '#ffffff',
      borderRadius: 8,
      padding: 10,
      alignItems: 'center',
      borderWidth: 1,
      borderColor: '#e9ecef',
      marginBottom: 8,
      position: 'relative',
    },
    serviceCardIcon: {
      width: 50,
      height: 50,
      borderRadius: 25,
      backgroundColor: '#F0F8FF',
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 8,
    },
    serviceCardName: {
      fontSize: 12,
      fontWeight: '600',
      color: '#212529',
      marginBottom: 2,
      textAlign: 'center',
    },
    serviceCardPrice: {
      fontSize: 10,
      color: '#8E8E93',
      textAlign: 'center',
    },
    servicesGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      gap: 6,
    },
    selectedServiceCard: {
      backgroundColor: '#4A90E2',
      borderColor: '#4A90E2',
    },
    selectedServiceCardIcon: {
      backgroundColor: 'rgba(255, 255, 255, 0.2)',
    },
    selectedServiceCardName: {
      color: '#ffffff',
    },
    selectedServiceCardPrice: {
      color: 'rgba(255, 255, 255, 0.8)',
    },
    selectedBadge: {
      position: 'absolute',
      top: 4,
      right: 4,
      width: 16,
      height: 16,
      borderRadius: 8,
      backgroundColor: '#34C759',
      justifyContent: 'center',
      alignItems: 'center',
    },
    serviceAmountCard: {
      backgroundColor: '#f8f9fa',
      borderRadius: 8,
      padding: 12,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: '#e9ecef',
    },
    serviceAmountHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 12,
    },
    serviceAmountInfo: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    serviceAmountName: {
      fontSize: 16,
      fontWeight: '600',
      color: '#212529',
    },
    serviceAmountValue: {
      fontSize: 16,
      fontWeight: 'bold',
      color: '#4A90E2',
    },
    totalAmountDisplay: {
      backgroundColor: '#4A90E2',
      borderRadius: 8,
      padding: 16,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginTop: 8,
    },
    totalAmountLabel: {
      fontSize: 16,
      fontWeight: '600',
      color: '#ffffff',
    },
    totalAmountValue: {
      fontSize: 18,
      fontWeight: 'bold',
      color: '#ffffff',
    },
    servicesList: {
      gap: 8,
    },
    serviceListItem: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      backgroundColor: '#ffffff',
      borderRadius: 8,
      padding: 12,
      borderWidth: 1,
      borderColor: '#e9ecef',
    },
    selectedServiceListItem: {
      backgroundColor: '#f0f8ff',
      borderColor: '#4A90E2',
    },
    serviceListLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      flex: 1,
    },
    serviceListIcon: {
      width: 36,
      height: 36,
      borderRadius: 18,
      backgroundColor: '#f0f8ff',
      justifyContent: 'center',
      alignItems: 'center',
      marginRight: 12,
    },
    selectedServiceListIcon: {
      backgroundColor: '#4A90E2',
    },
    serviceListInfo: {
      flex: 1,
    },
    serviceListName: {
      fontSize: 14,
      fontWeight: '600',
      color: '#212529',
      marginBottom: 2,
    },
    selectedServiceListName: {
      color: '#4A90E2',
    },
    serviceListPrice: {
      fontSize: 12,
      color: '#8E8E93',
    },
    selectedServiceListPrice: {
      color: '#4A90E2',
    },
    serviceCheckbox: {
      width: 20,
      height: 20,
      borderRadius: 10,
      borderWidth: 2,
      borderColor: '#e9ecef',
      justifyContent: 'center',
      alignItems: 'center',
    },
    selectedServiceCheckbox: {
      backgroundColor: '#4A90E2',
      borderColor: '#4A90E2',
    },
    servicesIconGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    serviceIconButton: {
      width: 80,
      height: 65,
      backgroundColor: '#f8f9fa',
      borderRadius: 10,
      borderWidth: 1,
      borderColor: '#e9ecef',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical: 8,
      position: 'relative',
    },
    selectedServiceIconButton: {
      backgroundColor: '#4A90E2',
      borderColor: '#4A90E2',
    },
    serviceIconText: {
      fontSize: 11,
      color: '#6c757d',
      marginTop: 3,
      textAlign: 'center',
      fontWeight: '500',
    },
    selectedServiceIconText: {
      color: '#ffffff',
      fontWeight: '500',
    },
    serviceIconBadge: {
      position: 'absolute',
      top: 4,
      right: 4,
      width: 16,
      height: 16,
      borderRadius: 8,
      backgroundColor: '#34C759',
      justifyContent: 'center',
      alignItems: 'center',
    },
  });